import { useEffect, useMemo, useState } from 'react'
import BorderGlow from './components/BorderGlow'
import GooeyNav from './components/GooeyNav'
import SpecularButton from './components/SpecularButton'

const media = {
  hero: 'https://macdonaldholdings.com/wp-content/uploads/2023/07/Steel-warehouse.jpg',
  shop: 'https://macdonaldholdings.com/wp-content/uploads/2023/09/macdonald-steel-shop-hero.jpg',
  columns: 'https://macdonaldholdings.com/wp-content/uploads/2023/07/columns.png',
  bars: 'https://macdonaldholdings.com/wp-content/uploads/2023/07/Round-Bar-MIld-Steel.png',
  sheet: 'https://macdonaldholdings.com/wp-content/uploads/2023/07/Galvanised-corrugated.jpg',
  plate: 'https://macdonaldholdings.com/wp-content/uploads/2023/07/mild-steel-plates-1-scaled-1.jpg',
  tube: 'https://macdonaldholdings.com/wp-content/uploads/2023/07/Steel-tubes.jpg',
  mesh: 'https://macdonaldholdings.com/wp-content/uploads/2023/07/Steel-warehouse.jpg',
  structural: '/structural-steel-premium.png',
  tubesPremium: '/tubes-bars-premium.png',
  sheetPremium: '/sheet-mesh-premium.png',
  channel: 'https://macdonaldholdings.com/wp-content/uploads/2023/07/Channels-scaled-1.jpg',
  en8Bar: 'https://macdonaldholdings.com/wp-content/uploads/2023/07/EN8-Bright-Round-Bar-scaled-1.jpg',
  reinforcing: 'https://macdonaldholdings.com/wp-content/uploads/2023/07/Reinforcing-Bar.png',
  galvSheet: 'https://macdonaldholdings.com/wp-content/uploads/2023/07/galvanised-sheet.png',
  diamondMesh: 'https://macdonaldholdings.com/wp-content/uploads/2023/07/Diamond-mesh-scaled-1.jpg',
  wandile: '/structural-steel-premium.png',
}
const products = [
  { name:'Angle iron', family:'Structural steel', image:media.channel, copy:'Reliable sections for fabrication, frames and supports.' },
  { name:'Universal beams & columns', family:'Structural steel', image:media.columns, copy:'Load-bearing profiles for serious structural work.' },
  { name:'Square, round & rectangular tube', family:'Tube & pipe', image:media.tube, copy:'Versatile hollow sections ready for your next build.' },
  { name:'Special steel, round & square bars', family:'Bar steel', image:media.en8Bar, copy:'Engineering bar for manufacturing and fabrication.' },
  { name:'Y-bars', family:'Reinforcing', image:media.reinforcing, copy:'Reinforcement steel for solid foundations.' },
  { name:'Sheet & plate', family:'Sheet products', image:media.plate, copy:'Steel sheet and plate for manufacturing and construction.' },
  { name:'Galv & Chromadek sheet', family:'Sheet products', image:media.galvSheet, copy:'Coated sheet products built for long-term performance.' },
  { name:'Expanded & fencing mesh', family:'Mesh & fencing', image:media.diamondMesh, copy:'Practical protection, screening and perimeter solutions.' },
]
const nav = [['home','Home'],['products','Products'],['industries','Industries'],['quality','Quality'],['diy','DIY Shop'],['wandile','Wandile Steel'],['contact','Contact']]

function SocialLinks(){return <div className="social-links"><a href="https://www.facebook.com/macdonaldsteelsa" target="_blank" rel="noreferrer" aria-label="Facebook"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M13.5 21v-8h2.7l.4-3h-3.1V8.1c0-.9.3-1.6 1.6-1.6h1.7V3.8c-.3 0-1.3-.1-2.5-.1-2.5 0-4.2 1.5-4.2 4.3v2H7.3v3h2.8v8h3.4Z"/></svg><span>Facebook</span></a><a href="https://www.linkedin.com/company/macdonald-steel-sa/" target="_blank" rel="noreferrer" aria-label="LinkedIn"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6.5 8.3H3.2V21h3.3V8.3ZM4.9 3A1.9 1.9 0 1 0 5 6.8 1.9 1.9 0 0 0 4.9 3ZM21 13.7c0-3.8-2-5.6-4.8-5.6-2.2 0-3.2 1.2-3.8 2.1V8.3H9.1V21h3.3v-6.3c0-1.7.3-3.3 2.4-3.3 2.1 0 2.1 1.9 2.1 3.4V21h3.3v-7.3Z"/></svg><span>LinkedIn</span></a><a href="https://www.instagram.com/macdonaldsteelsa/" target="_blank" rel="noreferrer" aria-label="Instagram"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7.4 2h9.2A5.4 5.4 0 0 1 22 7.4v9.2a5.4 5.4 0 0 1-5.4 5.4H7.4A5.4 5.4 0 0 1 2 16.6V7.4A5.4 5.4 0 0 1 7.4 2Zm-.2 2A3.2 3.2 0 0 0 4 7.2v9.6A3.2 3.2 0 0 0 7.2 20h9.6a3.2 3.2 0 0 0 3.2-3.2V7.2A3.2 3.2 0 0 0 16.8 4H7.2ZM12 7.3a4.7 4.7 0 1 1 0 9.4 4.7 4.7 0 0 1 0-9.4Zm0 2a2.7 2.7 0 1 0 0 5.4 2.7 2.7 0 0 0 0-5.4Zm5.1-3.4a1.1 1.1 0 1 1 0 2.2 1.1 1.1 0 0 1 0-2.2Z"/></svg><span>Instagram</span></a><a href="https://www.youtube.com/@macdonaldsteelsa6871" target="_blank" rel="noreferrer" aria-label="YouTube"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M22 12c0-2.6-.3-4.3-.8-5.2a2.8 2.8 0 0 0-2-2C17.8 4.4 12 4.4 12 4.4s-5.8 0-7.2.4a2.8 2.8 0 0 0-2 2C2.3 7.7 2 9.4 2 12s.3 4.3.8 5.2a2.8 2.8 0 0 0 2 2c1.4.4 7.2.4 7.2.4s5.8 0 7.2-.4a2.8 2.8 0 0 0 2-2c.5-.9.8-2.6.8-5.2Z"/><path fill="#fff" d="M9.7 8.2v7.6l6.2-3.8-6.2-3.8Z"/></svg><span>YouTube</span></a></div>}

function BrandButton({tone='red',children,className='',...props}){
  const palette={
    red:{lineColor:'#ffffff',baseColor:'#da202a'},
    dark:{lineColor:'#ffffff',baseColor:'#181818'},
    light:{lineColor:'#181818',baseColor:'#e2ded5'},
    success:{lineColor:'#ffffff',baseColor:'#16724e'},
  }[tone]
  return <SpecularButton radius={0} intensity={1.45} shineSize={12} shineFade={38} thickness={1.25} speed={.35} followMouse proximity={250} autoAnimate={false} className={className} {...palette} {...props}>{children}</SpecularButton>
}

function App(){
  const [page,setPage]=useState(location.hash.replace('#','')||'home'), [selected,setSelected]=useState(null)
  useEffect(()=>{ const listener=()=>setPage(location.hash.replace('#','')||'home'); addEventListener('hashchange',listener); return()=>removeEventListener('hashchange',listener)},[])
  useEffect(()=>{const elements=[...document.querySelectorAll('main section, main .ticker, main .lead-content, .catalogue-card, .industry-page article, .quality-cards article')];elements.forEach((element,index)=>{element.classList.add('reveal-ready');element.style.setProperty('--reveal-delay',`${Math.min(index%4,3)*70}ms`)});const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.08,rootMargin:'0px 0px -30px'});elements.forEach(element=>observer.observe(element));return()=>observer.disconnect()},[page])
  const go=(p)=>{location.hash=p;setPage(p);window.scrollTo({top:0,behavior:'smooth'})}
  const requestQuote=()=>{const showQuoteForm=()=>document.querySelector('.contact-page input[name="fullName"]')?.closest('label')?.scrollIntoView({behavior:'smooth',block:'start'});if(page!=='contact'){location.hash='contact';setPage('contact');setTimeout(showQuoteForm,80)}else{showQuoteForm()}}
  const navItems=nav.map(([id,label])=>({id,label,href:`#${id}`}))
  const activeNavIndex=Math.max(0,navItems.findIndex(item=>item.id===page))
  return <><header><div className="nav-wrap"><button className="logo-btn" onClick={()=>go('home')}><img src="/macdonald-steel-logo.png" alt="Macdonald Steel" /></button><GooeyNav items={navItems} activeIndex={activeNavIndex} onItemClick={item=>go(item.id)} particleCount={15} particleDistances={[90,10]} particleR={100} animationTime={600} timeVariance={300} colors={[1,2,3,1,2,3,1,4]}/><div className="nav-actions"><BrandButton className="quote-pill" onClick={requestQuote}>Request a quote <span>↗</span></BrandButton></div></div></header>
  {page==='home'&&<Home go={go} />}{page==='products'&&<Products select={setSelected} />}{page==='industries'&&<Industries go={go} />}{page==='quality'&&<Quality go={go} />}{page==='diy'&&<DIY go={go} />}{page==='wandile'&&<Wandile go={go} />}{page==='contact'&&<Contact />}
  {selected&&<ProductModal item={selected} close={()=>setSelected(null)} />}
  <footer><div className="footer-brand"><img src="/macdonald-steel-footer-logo.png" alt="Macdonald Steel"/><p>Steel solutions with<br/>the strength of experience.</p><SocialLinks/></div><div className="footer-links">{nav.map(([id,label])=><button onClick={()=>go(id)} key={id}>{label}</button>)}</div><div className="footer-contact"><strong>Contact</strong><a href="mailto:info@macdonaldsteelsa.com">Email: info@macdonaldsteelsa.com</a><a href="tel:+27314505200">Phone: 031 450 5200</a><div className="branch"><b>Main Branch</b><p>403 Chamberlain Rd, Jacobs,<br/>Durban, 4052</p></div><div className="branch"><b>Pietermaritzburg Branch</b><p>226 Ohrtmann Road, Willowton,<br/>Pietermaritzburg, 3201</p></div><div className="hours"><b>Operating hours</b><p><strong>Mon–Fri</strong> 7:30–16:30<br/><strong>Saturday</strong> 7:30–12:30</p></div></div><small>© {new Date().getFullYear()} Macdonald Steel. All Rights Reserved.</small></footer><a className="whatsapp-float" href="https://wa.me/27314505200" target="_blank" rel="noreferrer" aria-label="Chat with Macdonald Steel on WhatsApp"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M16 3a12.7 12.7 0 0 0-11 19l-1.5 5.5 5.6-1.5A12.8 12.8 0 1 0 16 3Zm0 23.2c-2 0-3.9-.6-5.5-1.5l-.4-.2-3.3.9.9-3.2-.2-.4A10.4 10.4 0 1 1 16 26.2Zm5.7-7.8c-.3-.2-1.8-.9-2.1-1-.3-.1-.5-.2-.7.2l-1 1.2c-.2.2-.4.2-.7.1a8.6 8.6 0 0 1-2.5-1.6 9.4 9.4 0 0 1-1.7-2.1c-.2-.3 0-.5.1-.6l.5-.6.3-.6c.1-.2 0-.4 0-.6l-1-2.3c-.2-.6-.5-.5-.7-.5h-.6c-.2 0-.6.1-.9.4-.3.3-1.2 1.2-1.2 2.9s1.2 3.3 1.4 3.5c.2.2 2.4 3.7 5.9 5.2.8.4 1.5.6 2 .7.8.3 1.6.2 2.2.1.7-.1 1.8-.8 2.1-1.5.3-.8.3-1.4.2-1.5-.1-.2-.3-.3-.6-.4Z"/></svg><span>WhatsApp</span></a></>
}

function PageLead({kicker,title,copy,image,children}){return <section className="page-lead" style={{'--bg':`url(${image})`}}><div className="darken"></div><div className="lead-content"><p className="kicker"><i></i>{kicker}</p><h1 dangerouslySetInnerHTML={{__html:title}}/><p className="lead-copy">{copy}</p>{children}</div></section>}
function Home({go}){return <main><PageLead kicker="Macdonald Steel · South Africa" title={'Steel for<br/><em>every</em> build.'} copy="A trusted steel and engineering partner since 1970 — supplying the materials, knowledge and commitment that move projects forward." image={media.hero}><div className="button-row"><BrandButton className="btn red" onClick={()=>go('products')}>Explore our range <b>↘</b></BrandButton><BrandButton tone="dark" className="btn text" onClick={()=>go('contact')}>Talk to an expert <b>→</b></BrandButton></div></PageLead><div className="ticker"><span>ANGLE IRON</span><span>UNIVERSAL BEAMS</span><span>STEEL TUBES</span><span>SHEET & PLATE</span><span>FENCING MESH</span></div><section className="statement"><div><p className="kicker"><i></i>Built on trust</p><h2>Not just a supplier.<br/>Your steel <em>partner.</em></h2></div><p>For more than five decades, Macdonald Steel has served Southern Africa’s industrial, construction and engineering sectors with practical, quality-focused solutions.</p></section><section className="featured"><div className="section-top"><p className="kicker"><i></i>Our range</p><BrandButton tone="dark" className="section-link-button" onClick={()=>go('products')}>See all products →</BrandButton></div><div className="feature-grid">{products.slice(0,4).map((p,i)=><BorderGlow key={p.name} className={`home-product-glow ${i===0?'wide':''}`} edgeSensitivity={30} glowColor="356 82 59" backgroundColor="#383838" borderRadius={0} glowRadius={34} glowIntensity={1.12} coneSpread={25} animated={false} colors={['#e12732','#413f3e','#ffffff']}><article style={{backgroundImage:`linear-gradient(0deg,rgba(10,10,10,.72),transparent 70%),url(${p.image})`}}><span>0{i+1}</span><h3>{p.name}</h3><button onClick={()=>go('products')}>View product ↗</button></article></BorderGlow>)}</div></section><section className="numbers"><div><b>50<span>+</span></b><p>Years serving<br/>Southern Africa</p></div><div><b>ISO</b><p>9001:2015<br/>Certified quality</p></div><div><b>8</b><p>Core steel<br/>product families</p></div><BrandButton tone="light" className="quality-link-button" onClick={()=>go('quality')}>Discover our quality commitment <b>→</b></BrandButton></section></main>}
function Products({select}){const [filter,setFilter]=useState('All');const families=['All',...new Set(products.map(p=>p.family))];const shown=useMemo(()=>filter==='All'?products:products.filter(p=>p.family===filter),[filter]);return <main><PageLead kicker="The Macdonald Steel range" title={'Built to spec.<br/><em>Ready</em> to work.'} copy="A practical, comprehensive range of steel products for trade, industry and the serious DIYer." image={media.tube}/><section className="catalogue"><div className="filter-bar"><p>Browse the range <span>{shown.length} products</span></p><div>{families.map(f=><button key={f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{f}</button>)}</div></div><div className="catalogue-grid">{shown.map((p)=><article className="catalogue-card" key={p.name}><BorderGlow className="product-image-glow" edgeSensitivity={30} glowColor="356 82 59" backgroundColor="#e8e5de" borderRadius={0} glowRadius={30} glowIntensity={1.05} coneSpread={25} animated={false} colors={['#e12732','#413f3e','#ffffff']}><div className="card-img"><img src={p.image} alt={p.name}/></div></BorderGlow><p>{p.family}</p><h2>{p.name}</h2><small>{p.copy}</small><div><button onClick={()=>select(p)}>Product details</button><button className="add" onClick={()=>select(p)} aria-label={`View details for ${p.name}`}>+</button></div></article>)}</div></section></main>}
function Industries({go}){const items=['Mining & minerals','Construction','Manufacturing','Infrastructure','Agriculture & fencing'];return <main><PageLead kicker="Sectors we serve" title={'Proven where<br/>it <em>counts.</em>'} copy="From bulk supply to specialist project requirements, our team understands the practical realities of your sector." image={media.shop}/><section className="industry-page"><p className="kicker"><i></i>Industry expertise</p>{items.map((x,i)=><article key={x}><span>0{i+1}</span><h2>{x}</h2><p>Quality steel products, knowledgeable support and reliable supply for demanding projects.</p><button onClick={()=>go('contact')}>Enquire <b>→</b></button></article>)}</section></main>}
function Quality({go}){return <main><PageLead kicker="Our commitment" title={'Quality you<br/>can <em>build on.</em>'} copy="We are committed to responsible business, reliable supply and the high standards our clients expect from every order." image={media.plate}/><section className="quality-page"><div><span>01</span><h2>Quality-led<br/>from the start.</h2><p>Our approach is built around consistent service, careful product selection and a commitment to long-term client value.</p></div><div className="quality-cards"><article><b>ISO</b><h3>9001:2015</h3><p>Quality-management systems that support dependable supply.</p></article><article><b>50+</b><h3>Years in steel</h3><p>Experience that makes the difference when it matters.</p></article><article><b>SA</b><h3>Local expertise</h3><p>Serving engineering and construction across Southern Africa.</p></article></div><BrandButton className="btn red" onClick={()=>go('contact')}>Work with our team <b>↗</b></BrandButton></section></main>}
function DIY({go}){return <main><PageLead kicker="Macdonald Steel DIY Shop" title={'Make it.<br/><em>Build</em> it.'} copy="Practical steel products and straight-talking help for builders, makers, repairers and DIYers." image={media.shop}><BrandButton className="btn red" onClick={()=>go('contact')}>Ask about stock <b>↗</b></BrandButton></PageLead><section className="diy-page"><div><p className="kicker"><i></i>For the hands-on</p><h2>Steel for projects<br/>of every <em>size.</em></h2><p>Whether you are securing a boundary, repairing a gate or starting a new fabrication project, our team can point you to the right product.</p></div><div className="diy-list"><span>Angle iron & bar</span><span>Tube sections</span><span>Galvanised sheet</span><span>Fencing & mesh</span><span>Sheet & plate</span></div></section></main>}
function Wandile({go}){return <main><PageLead kicker="Wandile Steel · Building more, together" title={'Steel value,<br/><em>delivered</em> together.'} copy="A Level 1 B-BBEE steel and metal supplier serving construction and engineering requirements from Durban to a national footprint." image={media.wandile}><BrandButton className="btn red" onClick={()=>go('contact')}>Enquire with our team <b>↗</b></BrandButton></PageLead><section className="wandile-page"><div><p className="kicker"><i></i>Wandile Steel</p><h2>Customer-first<br/>supply <em>solutions.</em></h2><p>Wandile Steel supplies ferrous and non-ferrous steel products, including aluminium extrusion solutions, through an efficient sourcing and contract-management model.</p></div><div className="wandile-points"><article><b>01</b><span>Level 1 B-BBEE</span></article><article><b>02</b><span>National footprint</span></article><article><b>03</b><span>Durban headquarters</span></article><article><b>04</b><span>Construction and engineering supply</span></article></div></section></main>}
function Contact(){const [status,setStatus]=useState('idle');const submit=e=>{e.preventDefault();if(status!=='idle')return;setStatus('sending');setTimeout(()=>setStatus('sent'),950)};return <main><PageLead kicker="Let’s get to work" title={'Bring us your<br/><em>next</em> brief.'} copy="Tell us what you need and our team will get back to you with the right direction." image={media.hero}/><section className="contact-page"><div><p className="kicker"><i></i>Contact Macdonald Steel</p><h2>Let’s talk<br/><em>steel.</em></h2><p>Email <a href="mailto:info@macdonaldsteelsa.com">info@macdonaldsteelsa.com</a><br/>Call <a href="tel:+27314505200">031 450 5200</a></p><div className="contact-locations"><div><b>Jacobs — Main branch</b><span>403 Chamberlain Rd<br/>Jacobs, Durban, 4052</span></div><div><b>Pietermaritzburg branch</b><span>226 Ohrtmann Road, Willowton<br/>Pietermaritzburg, 3201</span></div></div><p>Monday–Friday: 7:30–16:30<br/>Saturday: 7:30–12:30</p></div><form onSubmit={submit}><label>Full name<input name="fullName" required placeholder="Your name"/></label><label>Email address<input required type="email" placeholder="you@company.co.za"/></label><label>Phone number<input required type="tel" placeholder="Your phone number"/></label><label>Preferred branch<select required defaultValue=""><option value="" disabled>Select a branch</option><option>Jacobs — Main branch</option><option>Pietermaritzburg branch</option></select></label><label>Company <span className="optional">(optional)</span><input placeholder="Company name"/></label><label>Address <span className="optional">(optional)</span><textarea className="short-address" placeholder="Street address, suburb and city"></textarea></label><label>What do you need?<textarea required placeholder="Tell us about the products or project"></textarea></label><BrandButton tone={status==='sent'?'success':'red'} type="submit" className={`btn red enquiry-submit ${status}`} disabled={status!=='idle'}>{status==='idle'&&<>Send enquiry <b>↗</b></>}{status==='sending'&&<>Sending <i className="submit-spinner"/></>}{status==='sent'&&<>Enquiry received <b>✓</b></>}</BrandButton><p className="form-status" aria-live="polite">{status==='sent'?'Thank you. The Macdonald Steel team will be in touch.':''}</p></form></section></main>}
function ProductModal({item,close}){return <div className="modal-backdrop" onClick={close}><article className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><img src={item.image} alt={item.name}/><div><p className="kicker"><i></i>{item.family}</p><h2>{item.name}</h2><p>{item.copy}</p></div></article></div>}
export default App
